# absolute path to the project folder
project-folder: /proj/project_2000968/FAANG_lncRNA

# species name
species: bos_taurus

# absolute path to sample sheet (list of sample identifiers)
samples: /proj/project_2000968/FAANG_lncRNA/bos_taurus/samples

# absolute path to list of reference files (header of tsv: species, genome, index, annot)
ref: /proj/project_2000968/FAANG_lncRNA/pipeline/species_resources.tsv

params:
  cutadapt:
    # threshold used for quality trimming
    phread_score: "30"
    # path to file containing adapter sequence that might be ligated to 3' end of R1 reads
    adapter_R1: "/home/projects/neurostem/projects/rnaseq_pipelines/data/polyA/20190128_PSEN1_fAD/adapters_fw.fa"
    # path to file containing adapter sequence that might be ligated to 3' end of R2 reads
    adapter_R2: "/home/projects/neurostem/projects/rnaseq_pipelines/data/polyA/20190128_PSEN1_fAD/adapters_rv.fa"
    # reads shorter than this length are discarded
    min_length: "20"
    # if "any" then the pair is discarded if one of the reads meet the filtering criterium
    pair_filter: "any"
  fastqc: ""
  star: ""
  feelnc: ""
  stringtie:
    # Define here the tpm threshold for the merging step
    tpm: "1"
  rsem: ""
